"""The ONE shared preprocessing spec (P2, Section 2.2; AGENTS.md §8.0).

Train/serve skew is controlled in one place: this module is the source of
truth for resize + normalization. Training consumes it via
``training/common/dataset.py``; the endpoint custom handler
(``deploy/vision_endpoint/``, Section 2.4) consumes the exported JSON. The
committed ``preprocessing_spec.json`` next to this file is generated by
``export_spec`` and drift-checked by a unit test — change the spec HERE,
never in the handler.

Normalization uses ImageNet stats because both backbones are fine-tuned
from ImageNet-pretrained weights and expect them.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

SPEC_PATH = Path(__file__).with_name("preprocessing_spec.json")


@dataclass(frozen=True)
class PreprocessingSpec:
    image_size: int = 512  # square resize target for both models
    resize_filter: str = "bilinear"  # images
    mask_resize_filter: str = "nearest"  # masks — never interpolate labels
    mean: tuple[float, float, float] = (0.485, 0.456, 0.406)  # ImageNet
    std: tuple[float, float, float] = (0.229, 0.224, 0.225)  # ImageNet

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2) + "\n"

    @staticmethod
    def from_json(payload: str) -> PreprocessingSpec:
        data = json.loads(payload)
        data["mean"] = tuple(data["mean"])
        data["std"] = tuple(data["std"])
        return PreprocessingSpec(**data)


def load_spec(path: Path = SPEC_PATH) -> PreprocessingSpec:
    return PreprocessingSpec.from_json(path.read_text(encoding="utf-8"))


def export_spec(path: Path = SPEC_PATH) -> None:
    path.write_text(PreprocessingSpec().to_json(), encoding="utf-8")


if __name__ == "__main__":
    export_spec()
    print(f"wrote {SPEC_PATH}")
